# Generated by Django 4.2.1 on 2023-05-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='user_id',
            field=models.UUIDField(null=True, unique=True, verbose_name='ID пользователя'),
        ),
        migrations.AddIndex(
            model_name='consumer',
            index=models.Index(fields=['user_id', 'email'], name='consumer_user_id_email_idx'),
        ),
        migrations.AddIndex(
            model_name='consumer',
            index=models.Index(fields=['remote_consumer_id'], name='consumer_remote_consumer_idx'),
        ),
    ]
