# Generated by Django 4.2.1 on 2023-05-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['modified_subscribe_date'], name='filmwork_subscribe_date_idx'),
        ),
    ]
