# Generated by Django 4.2.1 on 2023-05-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_consumer_user_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payment_transaction_id_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['consumer'], name='payment_consumer_idx'),
        ),
    ]
