# Generated by Django 4.2.1 on 2023-05-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_payment_payment_transaction_id_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='currency',
            field=models.CharField(choices=[('usd', 'Доллар США')], max_length=5, null=True, verbose_name='Тип валюты'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='interval',
            field=models.CharField(choices=[('month', 'месяц')], max_length=20, null=True, verbose_name='Интервал действия подписки'),
        ),
    ]
