# Generated by Django 4.2.1 on 2023-05-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_subscribe_currency_alter_subscribe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='product_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID продукта в платежной системе'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID цены в платежной системе'),
        ),
    ]
