# Generated by Django 4.2.1 on 2023-05-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_subscribe_product_id_alter_subscribe_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Подписка активна'),
        ),
    ]
